# Generated by Django 5.0.7 on 2024-07-29 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Номер id на сайте', models.IntegerField()),
                ('Заголовок', models.CharField(max_length=100)),
                ('Автор', models.CharField(max_length=20)),
                ('Количество просмотров', models.IntegerField(default=0)),
                ('Номер позиции', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
